/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as ConciergeRouteImport } from './routes/concierge'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAProposRouteImport } from './routes/_public/a-propos'
import { Route as PublicAccesRouteImport } from './routes/_public/acces'
import { Route as PublicConditionsRouteImport } from './routes/_public/conditions'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicDemandeRouteImport } from './routes/_public/demande'
import { Route as PublicDiagnosticRouteImport } from './routes/_public/diagnostic'
import { Route as PublicFaqRouteImport } from './routes/_public/faq'
import { Route as PublicTarifsRouteImport } from './routes/_public/tarifs'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminConciergesRouteImport } from './routes/admin/concierges'
import { Route as AdminDiagnosticsAutoRouteImport } from './routes/admin/diagnostics-auto'
import { Route as AdminGrilleRouteImport } from './routes/admin/grille'
import { Route as AdminPipelineRouteImport } from './routes/admin/pipeline'
import { Route as AdminQualificationRouteImport } from './routes/admin/qualification'
import { Route as AdminQuotasRouteImport } from './routes/admin/quotas'
import { Route as AdminRelancesRouteImport } from './routes/admin/relances'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAbonnementRouteImport } from './routes/app/abonnement'
import { Route as AppDevisRouteImport } from './routes/app/devis'
import { Route as AppDiagnosticAutoRouteImport } from './routes/app/diagnostic-auto'
import { Route as AppDiagnosticsRouteImport } from './routes/app/diagnostics'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AppEspaceMetierRouteImport } from './routes/app/espace-metier'
import { Route as AppLivrablesRouteImport } from './routes/app/livrables'
import { Route as AppMessagesRouteImport } from './routes/app/messages'
import { Route as AppPrestatairesRouteImport } from './routes/app/prestataires'
import { Route as AppRendezVousRouteImport } from './routes/app/rendez-vous'
import { Route as ConciergeIndexRouteImport } from './routes/concierge/index'
import { Route as ConciergeBesoinsRouteImport } from './routes/concierge/besoins'
import { Route as ConciergeDiagnosticsRouteImport } from './routes/concierge/diagnostics'
import { Route as ConciergeDocumentsRouteImport } from './routes/concierge/documents'
import { Route as ConciergeMessagesRouteImport } from './routes/concierge/messages'
import { Route as ConciergeMissionsRouteImport } from './routes/concierge/missions'
import { Route as ConciergePrestatairesRouteImport } from './routes/concierge/prestataires'
import { Route as ConciergeRendezVousRouteImport } from './routes/concierge/rendez-vous'
import { Route as ConciergeSuiviCommercialRouteImport } from './routes/concierge/suivi-commercial'
import { Route as PublicMissionsIndexRouteImport } from './routes/_public/missions/index'
import { Route as PublicMissionsCodeRouteImport } from './routes/_public/missions/$code'
import { Route as PublicSecteursIndexRouteImport } from './routes/_public/secteurs/index'
import { Route as PublicSecteursSectorRouteImport } from './routes/_public/secteurs/$sector'
import { Route as PublicSecteursEnseignementRouteImport } from './routes/_public/secteurs/enseignement'
import { Route as PublicSecteursSanteRouteImport } from './routes/_public/secteurs/sante'
import { Route as PublicSecteursTourismeRouteImport } from './routes/_public/secteurs/tourisme'
import { Route as AdminBesoinsIndexRouteImport } from './routes/admin/besoins/index'
import { Route as AdminClientsIndexRouteImport } from './routes/admin/clients/index'
import { Route as AdminClientsIdRouteImport } from './routes/admin/clients/$id'
import { Route as AdminDiagnosticsIndexRouteImport } from './routes/admin/diagnostics/index'
import { Route as AdminMissionsIndexRouteImport } from './routes/admin/missions/index'
import { Route as AdminPrestatairesIndexRouteImport } from './routes/admin/prestataires/index'
import { Route as AppBesoinsIndexRouteImport } from './routes/app/besoins/index'
import { Route as AppBesoinsIdRouteImport } from './routes/app/besoins/$id'
import { Route as AppMissionsIndexRouteImport } from './routes/app/missions/index'
import { Route as AppMissionsIdRouteImport } from './routes/app/missions/$id'
import { Route as AppTourismeBranchRouteImport } from './routes/app/tourisme/$branch'
import { Route as ConciergeEntreprisesIndexRouteImport } from './routes/concierge/entreprises/index'
import { Route as ConciergeEntreprisesIdRouteImport } from './routes/concierge/entreprises/$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeRoute = ConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAProposRoute = PublicAProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAccesRoute = PublicAccesRouteImport.update({
  id: '/acces',
  path: '/acces',
  getParentRoute: () => PublicRoute,
} as any)
const PublicConditionsRoute = PublicConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDemandeRoute = PublicDemandeRouteImport.update({
  id: '/demande',
  path: '/demande',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDiagnosticRoute = PublicDiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTarifsRoute = PublicTarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => PublicRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConciergesRoute = AdminConciergesRouteImport.update({
  id: '/concierges',
  path: '/concierges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiagnosticsAutoRoute = AdminDiagnosticsAutoRouteImport.update({
  id: '/diagnostics-auto',
  path: '/diagnostics-auto',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGrilleRoute = AdminGrilleRouteImport.update({
  id: '/grille',
  path: '/grille',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQualificationRoute = AdminQualificationRouteImport.update({
  id: '/qualification',
  path: '/qualification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotasRoute = AdminQuotasRouteImport.update({
  id: '/quotas',
  path: '/quotas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelancesRoute = AdminRelancesRouteImport.update({
  id: '/relances',
  path: '/relances',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAbonnementRoute = AppAbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => AppRoute,
} as any)
const AppDevisRoute = AppDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosticAutoRoute = AppDiagnosticAutoRouteImport.update({
  id: '/diagnostic-auto',
  path: '/diagnostic-auto',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosticsRoute = AppDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppEspaceMetierRoute = AppEspaceMetierRouteImport.update({
  id: '/espace-metier',
  path: '/espace-metier',
  getParentRoute: () => AppRoute,
} as any)
const AppLivrablesRoute = AppLivrablesRouteImport.update({
  id: '/livrables',
  path: '/livrables',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppPrestatairesRoute = AppPrestatairesRouteImport.update({
  id: '/prestataires',
  path: '/prestataires',
  getParentRoute: () => AppRoute,
} as any)
const AppRendezVousRoute = AppRendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => AppRoute,
} as any)
const ConciergeIndexRoute = ConciergeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConciergeRoute,
} as any)
const ConciergeBesoinsRoute = ConciergeBesoinsRouteImport.update({
  id: '/besoins',
  path: '/besoins',
  getParentRoute: () => ConciergeRoute,
} as any)
const ConciergeDiagnosticsRoute = ConciergeDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => ConciergeRoute,
} as any)
const ConciergeDocumentsRoute = ConciergeDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ConciergeRoute,
} as any)
const ConciergeMessagesRoute = ConciergeMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ConciergeRoute,
} as any)
const ConciergeMissionsRoute = ConciergeMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => ConciergeRoute,
} as any)
const ConciergePrestatairesRoute = ConciergePrestatairesRouteImport.update({
  id: '/prestataires',
  path: '/prestataires',
  getParentRoute: () => ConciergeRoute,
} as any)
const ConciergeRendezVousRoute = ConciergeRendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => ConciergeRoute,
} as any)
const ConciergeSuiviCommercialRoute =
  ConciergeSuiviCommercialRouteImport.update({
    id: '/suivi-commercial',
    path: '/suivi-commercial',
    getParentRoute: () => ConciergeRoute,
  } as any)
const PublicMissionsIndexRoute = PublicMissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMissionsCodeRoute = PublicMissionsCodeRouteImport.update({
  id: '/missions/$code',
  path: '/missions/$code',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSecteursIndexRoute = PublicSecteursIndexRouteImport.update({
  id: '/secteurs/',
  path: '/secteurs/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSecteursSectorRoute = PublicSecteursSectorRouteImport.update({
  id: '/secteurs/$sector',
  path: '/secteurs/$sector',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSecteursEnseignementRoute =
  PublicSecteursEnseignementRouteImport.update({
    id: '/secteurs/enseignement',
    path: '/secteurs/enseignement',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicSecteursSanteRoute = PublicSecteursSanteRouteImport.update({
  id: '/secteurs/sante',
  path: '/secteurs/sante',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSecteursTourismeRoute = PublicSecteursTourismeRouteImport.update({
  id: '/secteurs/tourisme',
  path: '/secteurs/tourisme',
  getParentRoute: () => PublicRoute,
} as any)
const AdminBesoinsIndexRoute = AdminBesoinsIndexRouteImport.update({
  id: '/besoins/',
  path: '/besoins/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIdRoute = AdminClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiagnosticsIndexRoute = AdminDiagnosticsIndexRouteImport.update({
  id: '/diagnostics/',
  path: '/diagnostics/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMissionsIndexRoute = AdminMissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrestatairesIndexRoute = AdminPrestatairesIndexRouteImport.update({
  id: '/prestataires/',
  path: '/prestataires/',
  getParentRoute: () => AdminRoute,
} as any)
const AppBesoinsIndexRoute = AppBesoinsIndexRouteImport.update({
  id: '/besoins/',
  path: '/besoins/',
  getParentRoute: () => AppRoute,
} as any)
const AppBesoinsIdRoute = AppBesoinsIdRouteImport.update({
  id: '/besoins/$id',
  path: '/besoins/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsIndexRoute = AppMissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsIdRoute = AppMissionsIdRouteImport.update({
  id: '/missions/$id',
  path: '/missions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTourismeBranchRoute = AppTourismeBranchRouteImport.update({
  id: '/tourisme/$branch',
  path: '/tourisme/$branch',
  getParentRoute: () => AppRoute,
} as any)
const ConciergeEntreprisesIndexRoute =
  ConciergeEntreprisesIndexRouteImport.update({
    id: '/entreprises/',
    path: '/entreprises/',
    getParentRoute: () => ConciergeRoute,
  } as any)
const ConciergeEntreprisesIdRoute = ConciergeEntreprisesIdRouteImport.update({
  id: '/entreprises/$id',
  path: '/entreprises/$id',
  getParentRoute: () => ConciergeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/concierge': typeof ConciergeRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/onboarding': typeof OnboardingRoute
  '/a-propos': typeof PublicAProposRoute
  '/acces': typeof PublicAccesRoute
  '/conditions': typeof PublicConditionsRoute
  '/contact': typeof PublicContactRoute
  '/demande': typeof PublicDemandeRoute
  '/diagnostic': typeof PublicDiagnosticRoute
  '/faq': typeof PublicFaqRoute
  '/tarifs': typeof PublicTarifsRoute
  '/admin/concierges': typeof AdminConciergesRoute
  '/admin/diagnostics-auto': typeof AdminDiagnosticsAutoRoute
  '/admin/grille': typeof AdminGrilleRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/qualification': typeof AdminQualificationRoute
  '/admin/quotas': typeof AdminQuotasRoute
  '/admin/relances': typeof AdminRelancesRoute
  '/app/abonnement': typeof AppAbonnementRoute
  '/app/devis': typeof AppDevisRoute
  '/app/diagnostic-auto': typeof AppDiagnosticAutoRoute
  '/app/diagnostics': typeof AppDiagnosticsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/espace-metier': typeof AppEspaceMetierRoute
  '/app/livrables': typeof AppLivrablesRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/prestataires': typeof AppPrestatairesRoute
  '/app/rendez-vous': typeof AppRendezVousRoute
  '/concierge/besoins': typeof ConciergeBesoinsRoute
  '/concierge/diagnostics': typeof ConciergeDiagnosticsRoute
  '/concierge/documents': typeof ConciergeDocumentsRoute
  '/concierge/messages': typeof ConciergeMessagesRoute
  '/concierge/missions': typeof ConciergeMissionsRoute
  '/concierge/prestataires': typeof ConciergePrestatairesRoute
  '/concierge/rendez-vous': typeof ConciergeRendezVousRoute
  '/concierge/suivi-commercial': typeof ConciergeSuiviCommercialRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/concierge/': typeof ConciergeIndexRoute
  '/missions/$code': typeof PublicMissionsCodeRoute
  '/secteurs/$sector': typeof PublicSecteursSectorRoute
  '/secteurs/enseignement': typeof PublicSecteursEnseignementRoute
  '/secteurs/sante': typeof PublicSecteursSanteRoute
  '/secteurs/tourisme': typeof PublicSecteursTourismeRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/app/besoins/$id': typeof AppBesoinsIdRoute
  '/app/missions/$id': typeof AppMissionsIdRoute
  '/app/tourisme/$branch': typeof AppTourismeBranchRoute
  '/concierge/entreprises/$id': typeof ConciergeEntreprisesIdRoute
  '/missions/': typeof PublicMissionsIndexRoute
  '/secteurs/': typeof PublicSecteursIndexRoute
  '/admin/besoins/': typeof AdminBesoinsIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/diagnostics/': typeof AdminDiagnosticsIndexRoute
  '/admin/missions/': typeof AdminMissionsIndexRoute
  '/admin/prestataires/': typeof AdminPrestatairesIndexRoute
  '/app/besoins/': typeof AppBesoinsIndexRoute
  '/app/missions/': typeof AppMissionsIndexRoute
  '/concierge/entreprises/': typeof ConciergeEntreprisesIndexRoute
}
export interface FileRoutesByTo {
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/onboarding': typeof OnboardingRoute
  '/a-propos': typeof PublicAProposRoute
  '/acces': typeof PublicAccesRoute
  '/conditions': typeof PublicConditionsRoute
  '/contact': typeof PublicContactRoute
  '/demande': typeof PublicDemandeRoute
  '/diagnostic': typeof PublicDiagnosticRoute
  '/faq': typeof PublicFaqRoute
  '/tarifs': typeof PublicTarifsRoute
  '/admin/concierges': typeof AdminConciergesRoute
  '/admin/diagnostics-auto': typeof AdminDiagnosticsAutoRoute
  '/admin/grille': typeof AdminGrilleRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/qualification': typeof AdminQualificationRoute
  '/admin/quotas': typeof AdminQuotasRoute
  '/admin/relances': typeof AdminRelancesRoute
  '/app/abonnement': typeof AppAbonnementRoute
  '/app/devis': typeof AppDevisRoute
  '/app/diagnostic-auto': typeof AppDiagnosticAutoRoute
  '/app/diagnostics': typeof AppDiagnosticsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/espace-metier': typeof AppEspaceMetierRoute
  '/app/livrables': typeof AppLivrablesRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/prestataires': typeof AppPrestatairesRoute
  '/app/rendez-vous': typeof AppRendezVousRoute
  '/concierge/besoins': typeof ConciergeBesoinsRoute
  '/concierge/diagnostics': typeof ConciergeDiagnosticsRoute
  '/concierge/documents': typeof ConciergeDocumentsRoute
  '/concierge/messages': typeof ConciergeMessagesRoute
  '/concierge/missions': typeof ConciergeMissionsRoute
  '/concierge/prestataires': typeof ConciergePrestatairesRoute
  '/concierge/rendez-vous': typeof ConciergeRendezVousRoute
  '/concierge/suivi-commercial': typeof ConciergeSuiviCommercialRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/concierge': typeof ConciergeIndexRoute
  '/missions/$code': typeof PublicMissionsCodeRoute
  '/secteurs/$sector': typeof PublicSecteursSectorRoute
  '/secteurs/enseignement': typeof PublicSecteursEnseignementRoute
  '/secteurs/sante': typeof PublicSecteursSanteRoute
  '/secteurs/tourisme': typeof PublicSecteursTourismeRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/app/besoins/$id': typeof AppBesoinsIdRoute
  '/app/missions/$id': typeof AppMissionsIdRoute
  '/app/tourisme/$branch': typeof AppTourismeBranchRoute
  '/concierge/entreprises/$id': typeof ConciergeEntreprisesIdRoute
  '/missions': typeof PublicMissionsIndexRoute
  '/secteurs': typeof PublicSecteursIndexRoute
  '/admin/besoins': typeof AdminBesoinsIndexRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/diagnostics': typeof AdminDiagnosticsIndexRoute
  '/admin/missions': typeof AdminMissionsIndexRoute
  '/admin/prestataires': typeof AdminPrestatairesIndexRoute
  '/app/besoins': typeof AppBesoinsIndexRoute
  '/app/missions': typeof AppMissionsIndexRoute
  '/concierge/entreprises': typeof ConciergeEntreprisesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/concierge': typeof ConciergeRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/onboarding': typeof OnboardingRoute
  '/_public/a-propos': typeof PublicAProposRoute
  '/_public/acces': typeof PublicAccesRoute
  '/_public/conditions': typeof PublicConditionsRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/demande': typeof PublicDemandeRoute
  '/_public/diagnostic': typeof PublicDiagnosticRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/tarifs': typeof PublicTarifsRoute
  '/admin/concierges': typeof AdminConciergesRoute
  '/admin/diagnostics-auto': typeof AdminDiagnosticsAutoRoute
  '/admin/grille': typeof AdminGrilleRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/qualification': typeof AdminQualificationRoute
  '/admin/quotas': typeof AdminQuotasRoute
  '/admin/relances': typeof AdminRelancesRoute
  '/app/abonnement': typeof AppAbonnementRoute
  '/app/devis': typeof AppDevisRoute
  '/app/diagnostic-auto': typeof AppDiagnosticAutoRoute
  '/app/diagnostics': typeof AppDiagnosticsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/espace-metier': typeof AppEspaceMetierRoute
  '/app/livrables': typeof AppLivrablesRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/prestataires': typeof AppPrestatairesRoute
  '/app/rendez-vous': typeof AppRendezVousRoute
  '/concierge/besoins': typeof ConciergeBesoinsRoute
  '/concierge/diagnostics': typeof ConciergeDiagnosticsRoute
  '/concierge/documents': typeof ConciergeDocumentsRoute
  '/concierge/messages': typeof ConciergeMessagesRoute
  '/concierge/missions': typeof ConciergeMissionsRoute
  '/concierge/prestataires': typeof ConciergePrestatairesRoute
  '/concierge/rendez-vous': typeof ConciergeRendezVousRoute
  '/concierge/suivi-commercial': typeof ConciergeSuiviCommercialRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/concierge/': typeof ConciergeIndexRoute
  '/_public/missions/$code': typeof PublicMissionsCodeRoute
  '/_public/secteurs/$sector': typeof PublicSecteursSectorRoute
  '/_public/secteurs/enseignement': typeof PublicSecteursEnseignementRoute
  '/_public/secteurs/sante': typeof PublicSecteursSanteRoute
  '/_public/secteurs/tourisme': typeof PublicSecteursTourismeRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/app/besoins/$id': typeof AppBesoinsIdRoute
  '/app/missions/$id': typeof AppMissionsIdRoute
  '/app/tourisme/$branch': typeof AppTourismeBranchRoute
  '/concierge/entreprises/$id': typeof ConciergeEntreprisesIdRoute
  '/_public/missions/': typeof PublicMissionsIndexRoute
  '/_public/secteurs/': typeof PublicSecteursIndexRoute
  '/admin/besoins/': typeof AdminBesoinsIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/diagnostics/': typeof AdminDiagnosticsIndexRoute
  '/admin/missions/': typeof AdminMissionsIndexRoute
  '/admin/prestataires/': typeof AdminPrestatairesIndexRoute
  '/app/besoins/': typeof AppBesoinsIndexRoute
  '/app/missions/': typeof AppMissionsIndexRoute
  '/concierge/entreprises/': typeof ConciergeEntreprisesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/concierge'
    | '/connexion'
    | '/inscription'
    | '/onboarding'
    | '/a-propos'
    | '/acces'
    | '/conditions'
    | '/contact'
    | '/demande'
    | '/diagnostic'
    | '/faq'
    | '/tarifs'
    | '/admin/concierges'
    | '/admin/diagnostics-auto'
    | '/admin/grille'
    | '/admin/pipeline'
    | '/admin/qualification'
    | '/admin/quotas'
    | '/admin/relances'
    | '/app/abonnement'
    | '/app/devis'
    | '/app/diagnostic-auto'
    | '/app/diagnostics'
    | '/app/documents'
    | '/app/espace-metier'
    | '/app/livrables'
    | '/app/messages'
    | '/app/prestataires'
    | '/app/rendez-vous'
    | '/concierge/besoins'
    | '/concierge/diagnostics'
    | '/concierge/documents'
    | '/concierge/messages'
    | '/concierge/missions'
    | '/concierge/prestataires'
    | '/concierge/rendez-vous'
    | '/concierge/suivi-commercial'
    | '/admin/'
    | '/app/'
    | '/concierge/'
    | '/missions/$code'
    | '/secteurs/$sector'
    | '/secteurs/enseignement'
    | '/secteurs/sante'
    | '/secteurs/tourisme'
    | '/admin/clients/$id'
    | '/app/besoins/$id'
    | '/app/missions/$id'
    | '/app/tourisme/$branch'
    | '/concierge/entreprises/$id'
    | '/missions/'
    | '/secteurs/'
    | '/admin/besoins/'
    | '/admin/clients/'
    | '/admin/diagnostics/'
    | '/admin/missions/'
    | '/admin/prestataires/'
    | '/app/besoins/'
    | '/app/missions/'
    | '/concierge/entreprises/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connexion'
    | '/inscription'
    | '/onboarding'
    | '/a-propos'
    | '/acces'
    | '/conditions'
    | '/contact'
    | '/demande'
    | '/diagnostic'
    | '/faq'
    | '/tarifs'
    | '/admin/concierges'
    | '/admin/diagnostics-auto'
    | '/admin/grille'
    | '/admin/pipeline'
    | '/admin/qualification'
    | '/admin/quotas'
    | '/admin/relances'
    | '/app/abonnement'
    | '/app/devis'
    | '/app/diagnostic-auto'
    | '/app/diagnostics'
    | '/app/documents'
    | '/app/espace-metier'
    | '/app/livrables'
    | '/app/messages'
    | '/app/prestataires'
    | '/app/rendez-vous'
    | '/concierge/besoins'
    | '/concierge/diagnostics'
    | '/concierge/documents'
    | '/concierge/messages'
    | '/concierge/missions'
    | '/concierge/prestataires'
    | '/concierge/rendez-vous'
    | '/concierge/suivi-commercial'
    | '/'
    | '/admin'
    | '/app'
    | '/concierge'
    | '/missions/$code'
    | '/secteurs/$sector'
    | '/secteurs/enseignement'
    | '/secteurs/sante'
    | '/secteurs/tourisme'
    | '/admin/clients/$id'
    | '/app/besoins/$id'
    | '/app/missions/$id'
    | '/app/tourisme/$branch'
    | '/concierge/entreprises/$id'
    | '/missions'
    | '/secteurs'
    | '/admin/besoins'
    | '/admin/clients'
    | '/admin/diagnostics'
    | '/admin/missions'
    | '/admin/prestataires'
    | '/app/besoins'
    | '/app/missions'
    | '/concierge/entreprises'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/app'
    | '/concierge'
    | '/connexion'
    | '/inscription'
    | '/onboarding'
    | '/_public/a-propos'
    | '/_public/acces'
    | '/_public/conditions'
    | '/_public/contact'
    | '/_public/demande'
    | '/_public/diagnostic'
    | '/_public/faq'
    | '/_public/tarifs'
    | '/admin/concierges'
    | '/admin/diagnostics-auto'
    | '/admin/grille'
    | '/admin/pipeline'
    | '/admin/qualification'
    | '/admin/quotas'
    | '/admin/relances'
    | '/app/abonnement'
    | '/app/devis'
    | '/app/diagnostic-auto'
    | '/app/diagnostics'
    | '/app/documents'
    | '/app/espace-metier'
    | '/app/livrables'
    | '/app/messages'
    | '/app/prestataires'
    | '/app/rendez-vous'
    | '/concierge/besoins'
    | '/concierge/diagnostics'
    | '/concierge/documents'
    | '/concierge/messages'
    | '/concierge/missions'
    | '/concierge/prestataires'
    | '/concierge/rendez-vous'
    | '/concierge/suivi-commercial'
    | '/_public/'
    | '/admin/'
    | '/app/'
    | '/concierge/'
    | '/_public/missions/$code'
    | '/_public/secteurs/$sector'
    | '/_public/secteurs/enseignement'
    | '/_public/secteurs/sante'
    | '/_public/secteurs/tourisme'
    | '/admin/clients/$id'
    | '/app/besoins/$id'
    | '/app/missions/$id'
    | '/app/tourisme/$branch'
    | '/concierge/entreprises/$id'
    | '/_public/missions/'
    | '/_public/secteurs/'
    | '/admin/besoins/'
    | '/admin/clients/'
    | '/admin/diagnostics/'
    | '/admin/missions/'
    | '/admin/prestataires/'
    | '/app/besoins/'
    | '/app/missions/'
    | '/concierge/entreprises/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ConciergeRoute: typeof ConciergeRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  InscriptionRoute: typeof InscriptionRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge': {
      id: '/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof ConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/a-propos': {
      id: '/_public/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof PublicAProposRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/acces': {
      id: '/_public/acces'
      path: '/acces'
      fullPath: '/acces'
      preLoaderRoute: typeof PublicAccesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/conditions': {
      id: '/_public/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof PublicConditionsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/demande': {
      id: '/_public/demande'
      path: '/demande'
      fullPath: '/demande'
      preLoaderRoute: typeof PublicDemandeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/diagnostic': {
      id: '/_public/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof PublicDiagnosticRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/tarifs': {
      id: '/_public/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof PublicTarifsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/concierges': {
      id: '/admin/concierges'
      path: '/concierges'
      fullPath: '/admin/concierges'
      preLoaderRoute: typeof AdminConciergesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diagnostics-auto': {
      id: '/admin/diagnostics-auto'
      path: '/diagnostics-auto'
      fullPath: '/admin/diagnostics-auto'
      preLoaderRoute: typeof AdminDiagnosticsAutoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grille': {
      id: '/admin/grille'
      path: '/grille'
      fullPath: '/admin/grille'
      preLoaderRoute: typeof AdminGrilleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/qualification': {
      id: '/admin/qualification'
      path: '/qualification'
      fullPath: '/admin/qualification'
      preLoaderRoute: typeof AdminQualificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotas': {
      id: '/admin/quotas'
      path: '/quotas'
      fullPath: '/admin/quotas'
      preLoaderRoute: typeof AdminQuotasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relances': {
      id: '/admin/relances'
      path: '/relances'
      fullPath: '/admin/relances'
      preLoaderRoute: typeof AdminRelancesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/abonnement': {
      id: '/app/abonnement'
      path: '/abonnement'
      fullPath: '/app/abonnement'
      preLoaderRoute: typeof AppAbonnementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/devis': {
      id: '/app/devis'
      path: '/devis'
      fullPath: '/app/devis'
      preLoaderRoute: typeof AppDevisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/diagnostic-auto': {
      id: '/app/diagnostic-auto'
      path: '/diagnostic-auto'
      fullPath: '/app/diagnostic-auto'
      preLoaderRoute: typeof AppDiagnosticAutoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/diagnostics': {
      id: '/app/diagnostics'
      path: '/diagnostics'
      fullPath: '/app/diagnostics'
      preLoaderRoute: typeof AppDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/espace-metier': {
      id: '/app/espace-metier'
      path: '/espace-metier'
      fullPath: '/app/espace-metier'
      preLoaderRoute: typeof AppEspaceMetierRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/livrables': {
      id: '/app/livrables'
      path: '/livrables'
      fullPath: '/app/livrables'
      preLoaderRoute: typeof AppLivrablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prestataires': {
      id: '/app/prestataires'
      path: '/prestataires'
      fullPath: '/app/prestataires'
      preLoaderRoute: typeof AppPrestatairesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rendez-vous': {
      id: '/app/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/app/rendez-vous'
      preLoaderRoute: typeof AppRendezVousRouteImport
      parentRoute: typeof AppRoute
    }
    '/concierge/': {
      id: '/concierge/'
      path: '/'
      fullPath: '/concierge/'
      preLoaderRoute: typeof ConciergeIndexRouteImport
      parentRoute: typeof ConciergeRoute
    }
    '/concierge/besoins': {
      id: '/concierge/besoins'
      path: '/besoins'
      fullPath: '/concierge/besoins'
      preLoaderRoute: typeof ConciergeBesoinsRouteImport
      parentRoute: typeof ConciergeRoute
    }
    '/concierge/diagnostics': {
      id: '/concierge/diagnostics'
      path: '/diagnostics'
      fullPath: '/concierge/diagnostics'
      preLoaderRoute: typeof ConciergeDiagnosticsRouteImport
      parentRoute: typeof ConciergeRoute
    }
    '/concierge/documents': {
      id: '/concierge/documents'
      path: '/documents'
      fullPath: '/concierge/documents'
      preLoaderRoute: typeof ConciergeDocumentsRouteImport
      parentRoute: typeof ConciergeRoute
    }
    '/concierge/messages': {
      id: '/concierge/messages'
      path: '/messages'
      fullPath: '/concierge/messages'
      preLoaderRoute: typeof ConciergeMessagesRouteImport
      parentRoute: typeof ConciergeRoute
    }
    '/concierge/missions': {
      id: '/concierge/missions'
      path: '/missions'
      fullPath: '/concierge/missions'
      preLoaderRoute: typeof ConciergeMissionsRouteImport
      parentRoute: typeof ConciergeRoute
    }
    '/concierge/prestataires': {
      id: '/concierge/prestataires'
      path: '/prestataires'
      fullPath: '/concierge/prestataires'
      preLoaderRoute: typeof ConciergePrestatairesRouteImport
      parentRoute: typeof ConciergeRoute
    }
    '/concierge/rendez-vous': {
      id: '/concierge/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/concierge/rendez-vous'
      preLoaderRoute: typeof ConciergeRendezVousRouteImport
      parentRoute: typeof ConciergeRoute
    }
    '/concierge/suivi-commercial': {
      id: '/concierge/suivi-commercial'
      path: '/suivi-commercial'
      fullPath: '/concierge/suivi-commercial'
      preLoaderRoute: typeof ConciergeSuiviCommercialRouteImport
      parentRoute: typeof ConciergeRoute
    }
    '/_public/missions/': {
      id: '/_public/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof PublicMissionsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/missions/$code': {
      id: '/_public/missions/$code'
      path: '/missions/$code'
      fullPath: '/missions/$code'
      preLoaderRoute: typeof PublicMissionsCodeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/secteurs/': {
      id: '/_public/secteurs/'
      path: '/secteurs'
      fullPath: '/secteurs/'
      preLoaderRoute: typeof PublicSecteursIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/secteurs/$sector': {
      id: '/_public/secteurs/$sector'
      path: '/secteurs/$sector'
      fullPath: '/secteurs/$sector'
      preLoaderRoute: typeof PublicSecteursSectorRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/secteurs/enseignement': {
      id: '/_public/secteurs/enseignement'
      path: '/secteurs/enseignement'
      fullPath: '/secteurs/enseignement'
      preLoaderRoute: typeof PublicSecteursEnseignementRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/secteurs/sante': {
      id: '/_public/secteurs/sante'
      path: '/secteurs/sante'
      fullPath: '/secteurs/sante'
      preLoaderRoute: typeof PublicSecteursSanteRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/secteurs/tourisme': {
      id: '/_public/secteurs/tourisme'
      path: '/secteurs/tourisme'
      fullPath: '/secteurs/tourisme'
      preLoaderRoute: typeof PublicSecteursTourismeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/besoins/': {
      id: '/admin/besoins/'
      path: '/besoins'
      fullPath: '/admin/besoins/'
      preLoaderRoute: typeof AdminBesoinsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/$id': {
      id: '/admin/clients/$id'
      path: '/clients/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AdminClientsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diagnostics/': {
      id: '/admin/diagnostics/'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics/'
      preLoaderRoute: typeof AdminDiagnosticsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/missions/': {
      id: '/admin/missions/'
      path: '/missions'
      fullPath: '/admin/missions/'
      preLoaderRoute: typeof AdminMissionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prestataires/': {
      id: '/admin/prestataires/'
      path: '/prestataires'
      fullPath: '/admin/prestataires/'
      preLoaderRoute: typeof AdminPrestatairesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/besoins/': {
      id: '/app/besoins/'
      path: '/besoins'
      fullPath: '/app/besoins/'
      preLoaderRoute: typeof AppBesoinsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/besoins/$id': {
      id: '/app/besoins/$id'
      path: '/besoins/$id'
      fullPath: '/app/besoins/$id'
      preLoaderRoute: typeof AppBesoinsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/missions/': {
      id: '/app/missions/'
      path: '/missions'
      fullPath: '/app/missions/'
      preLoaderRoute: typeof AppMissionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/missions/$id': {
      id: '/app/missions/$id'
      path: '/missions/$id'
      fullPath: '/app/missions/$id'
      preLoaderRoute: typeof AppMissionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tourisme/$branch': {
      id: '/app/tourisme/$branch'
      path: '/tourisme/$branch'
      fullPath: '/app/tourisme/$branch'
      preLoaderRoute: typeof AppTourismeBranchRouteImport
      parentRoute: typeof AppRoute
    }
    '/concierge/entreprises/': {
      id: '/concierge/entreprises/'
      path: '/entreprises'
      fullPath: '/concierge/entreprises/'
      preLoaderRoute: typeof ConciergeEntreprisesIndexRouteImport
      parentRoute: typeof ConciergeRoute
    }
    '/concierge/entreprises/$id': {
      id: '/concierge/entreprises/$id'
      path: '/entreprises/$id'
      fullPath: '/concierge/entreprises/$id'
      preLoaderRoute: typeof ConciergeEntreprisesIdRouteImport
      parentRoute: typeof ConciergeRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAProposRoute: typeof PublicAProposRoute
  PublicAccesRoute: typeof PublicAccesRoute
  PublicConditionsRoute: typeof PublicConditionsRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicDemandeRoute: typeof PublicDemandeRoute
  PublicDiagnosticRoute: typeof PublicDiagnosticRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicTarifsRoute: typeof PublicTarifsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicMissionsCodeRoute: typeof PublicMissionsCodeRoute
  PublicSecteursSectorRoute: typeof PublicSecteursSectorRoute
  PublicSecteursEnseignementRoute: typeof PublicSecteursEnseignementRoute
  PublicSecteursSanteRoute: typeof PublicSecteursSanteRoute
  PublicSecteursTourismeRoute: typeof PublicSecteursTourismeRoute
  PublicMissionsIndexRoute: typeof PublicMissionsIndexRoute
  PublicSecteursIndexRoute: typeof PublicSecteursIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAProposRoute: PublicAProposRoute,
  PublicAccesRoute: PublicAccesRoute,
  PublicConditionsRoute: PublicConditionsRoute,
  PublicContactRoute: PublicContactRoute,
  PublicDemandeRoute: PublicDemandeRoute,
  PublicDiagnosticRoute: PublicDiagnosticRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicTarifsRoute: PublicTarifsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicMissionsCodeRoute: PublicMissionsCodeRoute,
  PublicSecteursSectorRoute: PublicSecteursSectorRoute,
  PublicSecteursEnseignementRoute: PublicSecteursEnseignementRoute,
  PublicSecteursSanteRoute: PublicSecteursSanteRoute,
  PublicSecteursTourismeRoute: PublicSecteursTourismeRoute,
  PublicMissionsIndexRoute: PublicMissionsIndexRoute,
  PublicSecteursIndexRoute: PublicSecteursIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminConciergesRoute: typeof AdminConciergesRoute
  AdminDiagnosticsAutoRoute: typeof AdminDiagnosticsAutoRoute
  AdminGrilleRoute: typeof AdminGrilleRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminQualificationRoute: typeof AdminQualificationRoute
  AdminQuotasRoute: typeof AdminQuotasRoute
  AdminRelancesRoute: typeof AdminRelancesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientsIdRoute: typeof AdminClientsIdRoute
  AdminBesoinsIndexRoute: typeof AdminBesoinsIndexRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
  AdminDiagnosticsIndexRoute: typeof AdminDiagnosticsIndexRoute
  AdminMissionsIndexRoute: typeof AdminMissionsIndexRoute
  AdminPrestatairesIndexRoute: typeof AdminPrestatairesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConciergesRoute: AdminConciergesRoute,
  AdminDiagnosticsAutoRoute: AdminDiagnosticsAutoRoute,
  AdminGrilleRoute: AdminGrilleRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminQualificationRoute: AdminQualificationRoute,
  AdminQuotasRoute: AdminQuotasRoute,
  AdminRelancesRoute: AdminRelancesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientsIdRoute: AdminClientsIdRoute,
  AdminBesoinsIndexRoute: AdminBesoinsIndexRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
  AdminDiagnosticsIndexRoute: AdminDiagnosticsIndexRoute,
  AdminMissionsIndexRoute: AdminMissionsIndexRoute,
  AdminPrestatairesIndexRoute: AdminPrestatairesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAbonnementRoute: typeof AppAbonnementRoute
  AppDevisRoute: typeof AppDevisRoute
  AppDiagnosticAutoRoute: typeof AppDiagnosticAutoRoute
  AppDiagnosticsRoute: typeof AppDiagnosticsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEspaceMetierRoute: typeof AppEspaceMetierRoute
  AppLivrablesRoute: typeof AppLivrablesRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppPrestatairesRoute: typeof AppPrestatairesRoute
  AppRendezVousRoute: typeof AppRendezVousRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBesoinsIdRoute: typeof AppBesoinsIdRoute
  AppMissionsIdRoute: typeof AppMissionsIdRoute
  AppTourismeBranchRoute: typeof AppTourismeBranchRoute
  AppBesoinsIndexRoute: typeof AppBesoinsIndexRoute
  AppMissionsIndexRoute: typeof AppMissionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAbonnementRoute: AppAbonnementRoute,
  AppDevisRoute: AppDevisRoute,
  AppDiagnosticAutoRoute: AppDiagnosticAutoRoute,
  AppDiagnosticsRoute: AppDiagnosticsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEspaceMetierRoute: AppEspaceMetierRoute,
  AppLivrablesRoute: AppLivrablesRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppPrestatairesRoute: AppPrestatairesRoute,
  AppRendezVousRoute: AppRendezVousRoute,
  AppIndexRoute: AppIndexRoute,
  AppBesoinsIdRoute: AppBesoinsIdRoute,
  AppMissionsIdRoute: AppMissionsIdRoute,
  AppTourismeBranchRoute: AppTourismeBranchRoute,
  AppBesoinsIndexRoute: AppBesoinsIndexRoute,
  AppMissionsIndexRoute: AppMissionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ConciergeRouteChildren {
  ConciergeBesoinsRoute: typeof ConciergeBesoinsRoute
  ConciergeDiagnosticsRoute: typeof ConciergeDiagnosticsRoute
  ConciergeDocumentsRoute: typeof ConciergeDocumentsRoute
  ConciergeMessagesRoute: typeof ConciergeMessagesRoute
  ConciergeMissionsRoute: typeof ConciergeMissionsRoute
  ConciergePrestatairesRoute: typeof ConciergePrestatairesRoute
  ConciergeRendezVousRoute: typeof ConciergeRendezVousRoute
  ConciergeSuiviCommercialRoute: typeof ConciergeSuiviCommercialRoute
  ConciergeIndexRoute: typeof ConciergeIndexRoute
  ConciergeEntreprisesIdRoute: typeof ConciergeEntreprisesIdRoute
  ConciergeEntreprisesIndexRoute: typeof ConciergeEntreprisesIndexRoute
}

const ConciergeRouteChildren: ConciergeRouteChildren = {
  ConciergeBesoinsRoute: ConciergeBesoinsRoute,
  ConciergeDiagnosticsRoute: ConciergeDiagnosticsRoute,
  ConciergeDocumentsRoute: ConciergeDocumentsRoute,
  ConciergeMessagesRoute: ConciergeMessagesRoute,
  ConciergeMissionsRoute: ConciergeMissionsRoute,
  ConciergePrestatairesRoute: ConciergePrestatairesRoute,
  ConciergeRendezVousRoute: ConciergeRendezVousRoute,
  ConciergeSuiviCommercialRoute: ConciergeSuiviCommercialRoute,
  ConciergeIndexRoute: ConciergeIndexRoute,
  ConciergeEntreprisesIdRoute: ConciergeEntreprisesIdRoute,
  ConciergeEntreprisesIndexRoute: ConciergeEntreprisesIndexRoute,
}

const ConciergeRouteWithChildren = ConciergeRoute._addFileChildren(
  ConciergeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ConciergeRoute: ConciergeRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  InscriptionRoute: InscriptionRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
