import React,{useMemo,useState} from 'react';
import {CheckCircle2,ChevronDown,ClipboardCheck,FileText,ShieldAlert,Stethoscope,Target,TrendingUp,UsersRound} from 'lucide-react';
import {ADEQUATION_CRITERIA,CHARGES_POSTES,DEROULE,DOCUMENTS,FORMATS,GARDE_FOUS,NOTATION,QUESTIONS,REGLES,TRANSPARENCE,VERSIONS,VOLETS,type DiagnosticQuestion} from './diagnosticData';

type Answer={score:number;comment:string};
type Charge={supplier:string;annual:string;renewal:string;notice:string;compared:string;saving:string};
type Follow={deadline:string;action:string;indicator:string;owner:string;status:string;date:string};
type Adequation={score:number;comment:string};
type DiagnosticState={
 meta:{structure:string;date:string;contact:string;animator:string;decider:string;citySize:string;accepted:boolean;format:'Complet'|'Express ★'};
 answers:Record<string,Answer>;
 charges:Record<string,Charge>;
 roots:string[]; solutions:string[]; checks:string[]; decisions:string; reportDate:string; nextMeeting:string;
 follow:Follow[]; recheck:{initial:string;j90:string;gain:string}[];
 adequation:Record<string,Adequation>; adequationNext:string; satisfaction:string;
};

const KEY='allneeds.health.diagnostic.360.v5.1';
const empty=():DiagnosticState=>({
 meta:{structure:'Centre Atlas Santé',date:new Date().toISOString().slice(0,10),contact:'',animator:'',decider:'',citySize:'Casablanca · ',accepted:false,format:'Complet'},
 answers:Object.fromEntries(QUESTIONS.map(q=>[q.id,{score:0,comment:''}])),
 charges:Object.fromEntries(CHARGES_POSTES.map(x=>[x,{supplier:'',annual:'',renewal:'',notice:'',compared:'',saving:''}])),
 roots:['','',''],solutions:['','',''],checks:['','',''],decisions:'',reportDate:'',nextMeeting:'',
 follow:['J+30','J+30','J+60','J+60','J+90','J+90'].map(deadline=>({deadline,action:'',indicator:'',owner:'',status:'',date:''})),
 recheck:[0,1,2].map(()=>({initial:'',j90:'',gain:''})),
 adequation:Object.fromEntries(ADEQUATION_CRITERIA.map(x=>[x,{score:0,comment:''}])),adequationNext:'',satisfaction:''
});
function load(){try{const v=JSON.parse(localStorage.getItem(KEY)||'null');return v&&v.meta&&v.answers?{...empty(),...v}:empty()}catch{return empty()}}
const fmt=(n:number)=>Number.isFinite(n)?Math.round(n*10)/10:0;

export function Diagnostic360(){
 const [data,setData]=useState<DiagnosticState>(load),[tab,setTab]=useState<'cadre'|'questions'|'synthese'|'suivi'|'adequation'>('cadre'),[openVolet,setOpenVolet]=useState(1);
 const persist=(next:DiagnosticState)=>{setData(next);localStorage.setItem(KEY,JSON.stringify(next))};
 const updateMeta=(k:keyof DiagnosticState['meta'],v:any)=>persist({...data,meta:{...data.meta,[k]:v}});
 const setAnswer=(id:string,k:keyof Answer,v:string|number)=>persist({...data,answers:{...data.answers,[id]:{...data.answers[id],[k]:v}}});
 const visibleQuestions=data.meta.format==='Express ★'?QUESTIONS.filter(q=>q.starred):QUESTIONS;
 const stats=useMemo(()=>{
  const byVolet=VOLETS.map(v=>{
   const qs=QUESTIONS.filter(q=>Number(q.id[0])===v.id),internal=qs.filter(q=>q.internal),external=qs.filter(q=>!q.internal);
   const calc=(arr:DiagnosticQuestion[])=>{const scores=arr.map(q=>data.answers[q.id]?.score||0),noted=scores.filter(x=>x>0);return {total:noted.reduce((a,b)=>a+b,0),avg:noted.length?noted.reduce((a,b)=>a+b,0)/noted.length:0,index:noted.length?noted.reduce((a,b)=>a+b,0)/(5*noted.length)*100:0,coverage:noted.length,zeros:scores.filter(x=>x===0).length}};
   return {v,internal:calc(internal),external:calc(external),conclusive:internal.filter(q=>(data.answers[q.id]?.score||0)===0).length<=2};
  });
  const internal=QUESTIONS.filter(q=>q.internal).map(q=>({q,s:data.answers[q.id]?.score||0,priority:(5-(data.answers[q.id]?.score||0))*(q.weight||0)})).filter(x=>x.s>0);
  const external=QUESTIONS.filter(q=>!q.internal).map(q=>({q,s:data.answers[q.id]?.score||0,gap:(5-(data.answers[q.id]?.score||0))*(q.enjeu||0)})).filter(x=>x.s>0);
  const forces=internal.filter(x=>x.s>=4).sort((a,b)=>b.s-a.s||(b.q.weight||0)-(a.q.weight||0)).slice(0,3);
  const weaknesses=internal.filter(x=>x.s<=2).sort((a,b)=>a.s-b.s||(b.q.weight||0)-(a.q.weight||0)).slice(0,3);
  const priorities=[...internal].sort((a,b)=>b.priority-a.priority).slice(0,3);
  const opportunities=external.filter(x=>x.q.type==='Opportunité'&&x.s<=3).sort((a,b)=>b.gap-a.gap).slice(0,3);
  const threats=external.filter(x=>x.q.type==='Menace'&&x.s<=3).sort((a,b)=>b.gap-a.gap).slice(0,3);
  return {byVolet,forces,weaknesses,priorities,opportunities,threats};
 },[data.answers]);
 const adequationScore=ADEQUATION_CRITERIA.reduce((a,c)=>a+(data.adequation[c]?.score||0),0);
 const recommendation=adequationScore>=9?'PERFORMANCE ou PRO.':adequationScore>=6?'PRO, ou PRO puis Accès.':adequationScore>=3?'Accès CONNECT ou PLUS pour les besoins détectés.':'Restituer le diagnostic, garder le contact, aucune offre proposée.';
 const tabs=[['cadre','Cadre & méthode'],['questions','40 questions'],['synthese','Synthèse'],['suivi','J+30 / 60 / 90'],['adequation','Adéquation ALLNEEDS']] as const;
 return <section className="diag360">
  <div className="diag-hero"><div><span className="eyebrow">GRILLE DE DIAGNOSTIC 360° · SANTÉ · v5.1</span><h2>Du constat à la prochaine action, sans raccourci.</h2><p>4 volets · 40 questions (28 internes, 12 externes) · notation de 0 à 5 · commentaire par question · relances · synthèse forces, faiblesses, opportunités, menaces.</p></div><div className="diag-summary"><strong>{QUESTIONS.filter(q=>(data.answers[q.id]?.score||0)>0).length}/40</strong><span>questions notées</span><small>{data.meta.format}</small></div></div>
  <div className="diag-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>

  {tab==='cadre'&&<div className="diag-stack">
   <section className="diag-card"><div className="diag-card-title"><FileText/><div><h3>Identification du diagnostic</h3><p>Cadre de travail à compléter avant l’ouverture.</p></div></div><div className="diag-form-grid">
    <label>Structure<input value={data.meta.structure} onChange={e=>updateMeta('structure',e.target.value)}/></label><label>Date<input type="date" value={data.meta.date} onChange={e=>updateMeta('date',e.target.value)}/></label><label>Interlocuteur / fonction<input value={data.meta.contact} onChange={e=>updateMeta('contact',e.target.value)}/></label><label>Animateur ALLNEEDS<input value={data.meta.animator} onChange={e=>updateMeta('animator',e.target.value)}/></label><label>Décideur présent ? (oui / non)<input value={data.meta.decider} onChange={e=>updateMeta('decider',e.target.value)}/></label><label>Ville / effectif<input value={data.meta.citySize} onChange={e=>updateMeta('citySize',e.target.value)}/></label>
   </div></section>
   <section className="diag-card"><div className="diag-card-title"><ShieldAlert/><div><h3>Cadre et transparence</h3><p>À lire au client en ouverture.</p></div></div><ul className="diag-list">{TRANSPARENCE.map(x=><li key={x}>{x}</li>)}</ul><label className="diag-consent"><input type="checkbox" checked={data.meta.accepted} onChange={e=>updateMeta('accepted',e.target.checked)}/> Cadre lu et accepté par le décideur. <em>(Texte sur les données à faire valider par un conseil juridique avant la première utilisation.)</em></label></section>
   <section className="diag-card"><div className="diag-card-title"><ClipboardCheck/><div><h3>Avant le rendez-vous : documents à demander</h3><p>Le diagnostic n’utilise que les éléments nécessaires et non nominatifs.</p></div></div><ul className="diag-list two">{DOCUMENTS.map(x=><li key={x}>{x}</li>)}</ul></section>
   <section className="diag-card"><div className="diag-card-title"><Target/><div><h3>Deux formats, une même grille</h3><p>Le décideur est présent au moins à la restitution de chaque volet et à la séance de synthèse. Les questions de terrain peuvent être traitées avec le responsable désigné.</p></div></div><div className="format-grid">{FORMATS.map(f=><button className={data.meta.format===f.format?'format active':'format'} key={f.format} onClick={()=>updateMeta('format',f.format)}><strong>{f.format}</strong><span>{f.contenu}</span><small>{f.duree}</small><em>{f.quand}</em></button>)}</div></section>
   <section className="diag-card"><div className="diag-card-title"><Stethoscope/><div><h3>Déroulé : 1 volet = 1 module de 90 minutes</h3><p>Format complet.</p></div></div><div className="diag-table-wrap"><table className="diag-table"><thead><tr><th>Durée</th><th>Bloc</th><th>Objectif</th></tr></thead><tbody>{DEROULE.map(r=><tr key={r[0]}>{r.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table></div></section>
   <section className="diag-card"><div className="diag-card-title"><ShieldAlert/><div><h3>Garde-fous Santé</h3><p>Non négociables pendant le diagnostic.</p></div></div><ul className="diag-list">{GARDE_FOUS.map(x=><li key={x}>{x}</li>)}</ul></section>
   <section className="diag-card"><div className="diag-card-title"><TrendingUp/><div><h3>Règles de notation</h3><p>0 est exclu du calcul de moyenne.</p></div></div><div className="score-grid">{NOTATION.map(n=><div key={n.note}><b>{n.note}</b><strong>{n.niveau}</strong><span>{n.type}</span></div>)}</div><h4>Règles communes pour tous les animateurs</h4><ul className="diag-list">{REGLES.map(x=><li key={x}>{x}</li>)}</ul><div className="reading-grid"><div><b>Interne (A, 7 par volet)</b><p>Niveau de maîtrise constaté de ce que la structure contrôle elle-même.</p><small>Note 4–5 : forces. Note 1–2 : faiblesses. Type = (5 − note) × poids : difficultés prioritaires.</small></div><div><b>Externe · Opportunité (B)</b><p>Niveau d’exploitation d’un potentiel réel de l’environnement.</p><small>Note 1–3 : opportunité détectée, classée par écart (5 − note) × enjeu.</small></div><div><b>Externe · Menace (B)</b><p>Niveau de protection face à un risque externe.</p><small>Note 1–2 : menace forte. Note 3 : à surveiller. Classement par écart (5 − note) × enjeu.</small></div></div></section>
  </div>}

  {tab==='questions'&&<div className="diag-stack"><section className="diag-card compact"><div className="question-toolbar"><div><strong>{data.meta.format}</strong><span>{visibleQuestions.length} questions affichées</span></div><small>★ = question du format Express. Poids : 3 = impact &gt; 5 % du CA ou des charges, 2 = de 2 à 5 %, 1 = &lt; 2 %. Type = (5 − note) × poids. Note 0 = non évalué, exclu de la moyenne. Relance = question de creusement à poser si la réponse reste vague.</small></div></section>
   {VOLETS.map(v=>{const qs=visibleQuestions.filter(q=>Number(q.id[0])===v.id),s=stats.byVolet.find(x=>x.v.id===v.id)!;return <section className="diag-card volet" key={v.id}><button className="volet-head" onClick={()=>setOpenVolet(openVolet===v.id?0:v.id)}><span><b>VOLET {v.id}</b><strong>{v.title}</strong><small>{v.subtitle}</small></span><span className="volet-metrics"><em>{fmt((s.internal.index*7+s.external.index*3)/10)}%</em><small>maîtrise indicative</small></span><ChevronDown className={openVolet===v.id?'rot':''}/></button>{openVolet===v.id&&<div className="question-list">{qs.map(q=><QuestionCard key={q.id} q={q} a={data.answers[q.id]} onChange={setAnswer}/>) }<VoletSummary v={v.id} stat={s}/>{v.id===2&&<p className="health-note">Note de cadre : la sollicitation d’avis, la publicité et la présence sur les réseaux sont encadrées pour les professions de santé. L’animateur constate le niveau de maîtrise, il ne recommande aucune action sans que le professionnel ait vérifié les règles applicables.</p>}</div>}</section>})}
  </div>}

  {tab==='synthese'&&<div className="diag-stack">
   <section className="diag-card"><div className="diag-card-title"><TrendingUp/><div><h3>Report global des notes</h3><p>Reporter ici les 40 notes pour classer : meilleures notes internes (forces), plus hauts scores de priorité (difficultés), écarts pondérés externes les plus élevés (opportunités, menaces).</p></div></div><div className="diag-table-wrap"><table className="diag-table"><thead><tr><th>Volet</th><th>Interne /35</th><th>Externe /15</th><th>Indice de maîtrise</th><th>Couverture</th><th>N° notés 0</th><th>Conclusif ?</th></tr></thead><tbody>{stats.byVolet.map(s=><tr key={s.v.id}><td>{s.v.id} · {s.v.title}</td><td>{s.internal.total} / 35</td><td>{s.external.total} / 15</td><td>{fmt((s.internal.total+s.external.total)/(5*(s.internal.coverage+s.external.coverage||1))*100)} %</td><td>{s.internal.coverage+s.external.coverage} / 10</td><td>{s.internal.zeros+s.external.zeros}</td><td>{s.conclusive?'oui':'non'}</td></tr>)}<tr className="total-row"><td><b>Total</b></td><td><b>{stats.byVolet.reduce((a,s)=>a+s.internal.total,0)} / 140</b></td><td><b>{stats.byVolet.reduce((a,s)=>a+s.external.total,0)} / 60</b></td><td>—</td><td>{stats.byVolet.reduce((a,s)=>a+s.internal.coverage+s.external.coverage,0)} / 40</td><td>{stats.byVolet.reduce((a,s)=>a+s.internal.zeros+s.external.zeros,0)}</td><td>—</td></tr></tbody></table></div></section>
   <section className="diag-card"><div className="diag-card-title"><CheckCircle2/><div><h3>Synthèse du diagnostic</h3><p>À remplir en séance de synthèse globale, à partir du report des 40 notes.</p></div></div><SynthesisBlock title="Forces (3)" help="Les 3 questions internes les mieux notées (4 ou 5), avec un exemple ou un chiffre cité. À note égale, retenir le poids le plus élevé. Si moins de 3, compléter avec les atouts externes notés 4 ou 5." items={stats.forces.map(x=>`${x.q.id} · ${x.q.title} — ${x.s}/5`)}/><SynthesisBlock title="Faiblesses (3)" help="Les 3 questions internes les moins bien notées (1 ou 2). À note égale, retenir le poids le plus élevé." items={stats.weaknesses.map(x=>`${x.q.id} · ${x.q.title} — ${x.s}/5`)}/><SynthesisBlock title="Opportunités (3)" help="Parmi les questions externes à type « Opportunité » notées 1 à 3, les 3 qui ont le plus fort écart pondéré (5 − note) × enjeu." items={stats.opportunities.map(x=>`${x.q.id} · ${x.q.title} — écart ${x.gap}`)}/><SynthesisBlock title="Menaces (3)" help="Parmi les questions externes à type « Menace » notées 1 à 3, les 3 qui ont le plus fort écart pondéré (5 − note) × enjeu. Note 1–2 : exposition forte. Note 3 : à surveiller." items={stats.threats.map(x=>`${x.q.id} · ${x.q.title} — écart ${x.gap}`)}/>
    <div className="synthesis-edit"><h4>Difficultés prioritaires (3) et causes racines</h4><p>Les 3 plus hauts scores de priorité parmi les questions internes : (5 − note) × poids. Pour chacune, poser 5 « pourquoi » en s’aidant de l’observation terrain et noter la cause racine avant toute solution.</p>{stats.priorities.map((x,i)=><label key={x.q.id}><b>{i+1}. Difficulté : {x.q.id} · {x.q.title} — score {x.priority}</b><textarea placeholder="Cause racine" value={data.roots[i]||''} onChange={e=>{const a=[...data.roots];a[i]=e.target.value;persist({...data,roots:a})}}/></label>)}</div>
    <div className="synthesis-edit"><h4>Points à vérifier</h4><p>Notes dont le commentaire signale un doute, un chiffre non vu ou un document manquant. Pour chacune : élément à fournir et date limite (15 jours).</p>{data.checks.map((x,i)=><textarea key={i} placeholder={`${i+1}. Élément à fournir + date limite`} value={x} onChange={e=>{const a=[...data.checks];a[i]=e.target.value;persist({...data,checks:a})}}/>)}</div>
    <div className="synthesis-edit"><h4>Solutions recommandées (3)</h4><p>Une solution par cause racine, appuyée si possible sur une force ou une opportunité. Pour chacune : action, responsable, délai, offre ALLNEEDS (STARTER, PRO, PERFORMANCE, Accès) ou « aucune offre nécessaire ». Les besoins d’achat (questions Accès notées 1 à 3, échéances &lt; 12 mois) alimentent l’offre Accès.</p>{data.solutions.map((x,i)=><textarea key={i} placeholder={`${i+1}. Action · Resp. · Délai · Offre`} value={x} onChange={e=>{const a=[...data.solutions];a[i]=e.target.value;persist({...data,solutions:a})}}/>)}</div>
    <div className="diag-form-grid"><label>Décisions et suites convenues<textarea value={data.decisions} onChange={e=>persist({...data,decisions:e.target.value})}/></label><label>Compte-rendu sous 48 h le<input type="date" value={data.reportDate} onChange={e=>persist({...data,reportDate:e.target.value})}/></label><label>Prochain rendez-vous le<input type="date" value={data.nextMeeting} onChange={e=>persist({...data,nextMeeting:e.target.value})}/></label></div>
   </section>
   <section className="diag-card"><div className="diag-card-title"><FileText/><div><h3>Charges récurrentes : relevé</h3><p>À remplir avec les factures. Chaque échéance de renouvellement dans les 12 mois est un besoin potentiel pour ALLNEEDS Accès. Le client reste libre de comparer ailleurs.</p></div></div><div className="diag-table-wrap"><table className="diag-table editable"><thead><tr><th>Poste</th><th>Fournisseur actuel</th><th>Coût annuel HT</th><th>Échéance</th><th>Date limite de préavis</th><th>Comparé ?</th><th>Économie visée</th></tr></thead><tbody>{CHARGES_POSTES.map(p=><tr key={p}><td>{p}</td>{(['supplier','annual','renewal','notice','compared','saving'] as const).map(k=><td key={k}><input value={data.charges[p][k]} onChange={e=>persist({...data,charges:{...data.charges,[p]:{...data.charges[p],[k]:e.target.value}}})}/></td>)}</tr>)}</tbody></table></div></section>
  </div>}

  {tab==='suivi'&&<div className="diag-stack"><section className="diag-card"><div className="diag-card-title"><UsersRound/><div><h3>Plan de suivi : J+30 · J+60 · J+90</h3><p>Le diagnostic ne s’arrête pas à la restitution. Chaque action retenue est suivie avec un indicateur « avant → après ». À J+90, les 3 difficultés prioritaires sont re-notées avec les mêmes repères.</p></div></div><div className="follow-grid">{data.follow.map((f,i)=><div className="follow-row" key={i}><b>{f.deadline}</b><input placeholder="Action suivie" value={f.action} onChange={e=>{const a=[...data.follow];a[i]={...f,action:e.target.value};persist({...data,follow:a})}}/><input placeholder="Indicateur (avant → après)" value={f.indicator} onChange={e=>{const a=[...data.follow];a[i]={...f,indicator:e.target.value};persist({...data,follow:a})}}/><input placeholder="Responsable" value={f.owner} onChange={e=>{const a=[...data.follow];a[i]={...f,owner:e.target.value};persist({...data,follow:a})}}/><select value={f.status} onChange={e=>{const a=[...data.follow];a[i]={...f,status:e.target.value};persist({...data,follow:a})}}><option value="">Statut</option><option>fait</option><option>en cours</option><option>bloqué</option></select><input type="date" value={f.date} onChange={e=>{const a=[...data.follow];a[i]={...f,date:e.target.value};persist({...data,follow:a})}}/></div>)}</div><h4>Re-notation à J+90</h4>{data.recheck.map((r,i)=><div className="recheck" key={i}><b>Difficulté {i+1}</b><input placeholder="Note initiale" value={r.initial} onChange={e=>{const a=[...data.recheck];a[i]={...r,initial:e.target.value};persist({...data,recheck:a})}}/><input placeholder="Note à J+90" value={r.j90} onChange={e=>{const a=[...data.recheck];a[i]={...r,j90:e.target.value};persist({...data,recheck:a})}}/><input placeholder="Économie ou gain chiffré" value={r.gain} onChange={e=>{const a=[...data.recheck];a[i]={...r,gain:e.target.value};persist({...data,recheck:a})}}/></div>)}</section></div>}

  {tab==='adequation'&&<div className="diag-stack">
   <section className="diag-card">
    <div className="diag-card-title"><Target/><div><h3>Fiche d’adéquation avec l’accompagnement ALLNEEDS</h3><p>Partagée avec le client. Notez chaque critère : 0 = non, 1 = partiellement, 2 = oui. Cette fiche explique pourquoi une formule est recommandée, ou pourquoi aucune ne l’est.</p></div></div>
    <div className="adequation-list">{ADEQUATION_CRITERIA.map(c=>{
      const a=data.adequation[c];
      return <div key={c}>
       <strong>{c}</strong>
       <select value={a.score} onChange={e=>persist({...data,adequation:{...data.adequation,[c]:{...a,score:Number(e.target.value)}}})}>
        <option value={0}>0 · non</option><option value={1}>1 · partiellement</option><option value={2}>2 · oui</option>
       </select>
       <input placeholder="Commentaire" value={a.comment} onChange={e=>persist({...data,adequation:{...data.adequation,[c]:{...a,comment:e.target.value}}})}/>
      </div>
    })}</div>
    <div className="score-matrix"><div><b>9 à 12</b><span>PERFORMANCE ou PRO.</span></div><div><b>6 à 8</b><span>PRO, ou PRO puis Accès.</span></div><div><b>3 à 5</b><span>Accès CONNECT ou PLUS pour les besoins détectés.</span></div><div><b>0 à 2</b><span>Restituer le diagnostic, garder le contact, aucune offre proposée.</span></div></div><p className="adequation-options">Recommandation : STARTER seul · PRO · PERFORMANCE · Accès (niveau) · aucune</p><div className="recommendation"><span>Score total</span><strong>{adequationScore} / 12</strong><p>{recommendation}</p><small>Repères à ajuster après les 10 premiers diagnostics. Une recommandation « aucune offre » est un résultat valide du diagnostic.</small></div>
    <div className="diag-form-grid"><label>Recommandation<input value={recommendation} readOnly/></label><label>Prochain rendez-vous / relance (date)<input type="date" value={data.adequationNext} onChange={e=>persist({...data,adequationNext:e.target.value})}/></label><label>Note de satisfaction du client (0 à 10)<input type="number" min="0" max="10" value={data.satisfaction} onChange={e=>persist({...data,satisfaction:e.target.value})}/></label></div>
   </section>
   <section className="diag-card"><div className="diag-card-title"><FileText/><div><h3>Journal des versions</h3><p>Référentiel de travail intégré sans modification de contenu.</p></div></div><div className="diag-table-wrap"><table className="diag-table"><thead><tr><th>Version</th><th>Date</th><th>Changements</th><th>Responsable</th></tr></thead><tbody>{VERSIONS.map(r=><tr key={r[0]}>{r.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table></div></section>
  </div>}
 </section>
}

function QuestionCard({q,a,onChange}:{q:DiagnosticQuestion;a:Answer;onChange:(id:string,k:keyof Answer,v:string|number)=>void}){
 const score=a?.score||0;return <article className={`question-card ${q.besoinAcces?'access-need':''}`}><div className="question-top"><span className="qid">{q.id}{q.starred?' ★':''}</span><div><h4>{q.title}</h4><p>{q.question}</p>{q.besoinAcces&&<b className="access-chip">BESOIN ACCÈS</b>}<small><b>Relance :</b> {q.relance}</small></div><div className="question-score"><label>Note 0–5<select value={score} onChange={e=>onChange(q.id,'score',Number(e.target.value))}>{[0,1,2,3,4,5].map(n=><option key={n} value={n}>{n}</option>)}</select></label><em>{q.internal?`Poids ${q.weight}`:`Enjeu ${q.enjeu} · ${q.type}`}</em></div></div><div className="level-grid">{q.levels.map((x,i)=><button key={i} className={score===i+1?'selected':''} onClick={()=>onChange(q.id,'score',i+1)}><b>{i+1}</b><span>{x}</span></button>)}</div><label className="question-comment">Commentaire (exemple, chiffre, document vu)<textarea value={a?.comment||''} onChange={e=>onChange(q.id,'comment',e.target.value)}/></label>{score>0&&<div className="calculated"><span>{q.internal?'Type / priorité':'Écart pondéré'}</span><strong>{(5-score)*(q.internal?(q.weight||0):(q.enjeu||0))}</strong>{!q.internal&&<em>{q.type}</em>}</div>}</article>
}
function VoletSummary({v,stat}:{v:number;stat:any}){const qs=QUESTIONS.filter(q=>Number(q.id[0])===v),forces=qs.filter(q=>q.internal&&(stat&&0===0)&&((JSON.parse(localStorage.getItem(KEY)||'null')?.answers?.[q.id]?.score||0)>=4)).map(q=>q.id),weak=qs.filter(q=>q.internal&&((JSON.parse(localStorage.getItem(KEY)||'null')?.answers?.[q.id]?.score||0)>0)&&((JSON.parse(localStorage.getItem(KEY)||'null')?.answers?.[q.id]?.score||0)<=2)).map(q=>q.id),zeros=qs.filter(q=>(JSON.parse(localStorage.getItem(KEY)||'null')?.answers?.[q.id]?.score||0)===0).map(q=>q.id);return <><div className="volet-summary"><strong>Volet {v}</strong><span>Interne : {stat.internal.total} / 35</span><span>Moyenne (hors 0) : {fmt(stat.internal.avg)} / 5</span><span>Indice de maîtrise : {fmt(stat.internal.index)} %</span><span>Couverture : {stat.internal.coverage} / 7</span><span>Externe : {stat.external.total} / 15</span><span>Couverture : {stat.external.coverage} / 3</span><span>Conclusif : {stat.conclusive?'oui':'non'}</span></div><div className="volet-detail"><span><b>Type haute interne :</b> N° notés 4–5 → Forces {forces.length?`(${forces.join(', ')})`:''}</span><span><b>Type basse interne :</b> N° notés 1–2 → Faiblesses {weak.length?`(${weak.join(', ')})`:''}</span><span><b>N° à 0 :</b> {zeros.join(', ')||'aucun'}</span><small>Indice de maîtrise (%) = somme des notes ÷ (5 × nombre de questions notées) × 100. Il permet de comparer les volets et les structures même si certaines questions sont à 0.</small></div></>}
function SynthesisBlock({title,help,items}:{title:string;help:string;items:string[]}){return <div className="synthesis-block"><div><h4>{title}</h4><p>{help}</p></div><ol>{[0,1,2].map(i=><li key={i}>{items[i]||'—'}</li>)}</ol></div>}
