import type { ReactNode } from 'react'
import { Link } from '@tanstack/react-router'
import { CalendarDays, FileText, Gauge, Home, Inbox, Network, Receipt, UserRound, UsersRound, Briefcase } from 'lucide-react'
import { useDemo } from '@/store/store'
import { PageHeader } from '@/components/layouts'
import { providerReasons } from '@/lib/operational'

const nav = [
  ['/expert','Accueil',Home],['/expert/demandes','Demandes',Inbox],['/expert/missions','Missions',Briefcase],['/expert/clients','Clients',UsersRound],['/expert/agenda','Agenda',CalendarDays],['/expert/propositions','Propositions',Receipt],['/expert/documents','Documents',FileText],['/expert/performance','Performance',Gauge],['/expert/profil','Profil',UserRound],
] as const

export function ExpertShell({children}:{children:ReactNode}){
 return <div className="expert-workspace"><aside><div className="expert-brand"><span>A</span><div><strong>ALLNEEDS</strong><small>Expert / Partenaire</small></div></div><nav>{nav.map(([to,label,Icon])=><Link key={to} to={to as any}><Icon size={16}/>{label}</Link>)}</nav><p>Environnement de travail partenaire — les données restent issues de la démo existante.</p></aside><main>{children}</main></div>
}

export function ExpertSection({kind}:{kind:'home'|'demandes'|'missions'|'clients'|'agenda'|'propositions'|'documents'|'performance'|'profil'}){
 const {state}=useDemo(); const provider=state.providers[0]; if(!provider) return <><PageHeader eyebrow="Expert / Partenaire" title="Aucun profil partenaire disponible." description="Ajoutez un prestataire dans les données de démonstration pour ouvrir cet espace."/></>; const needs=state.needs.filter(n=>n.candidateIds.includes(provider.id)); const orgIds=new Set(needs.map(n=>n.orgId)); const orgs=state.orgs.filter(o=>orgIds.has(o.id)); const quotes=state.quotes.filter(q=>q.providerId===provider.id); const meetings=state.meetings.filter(m=>orgIds.has(m.orgId)); const docs=state.documents.filter(d=>orgIds.has(d.orgId));
 if(kind==='home') return <><PageHeader eyebrow="Expert / Partenaire" title={`Bonjour ${provider.name}.`} description="Demandes, propositions et preuves regroupées dans un espace de travail contextuel."/><div className="expert-home-grid"><section><small>Demandes liées</small><strong>{needs.length}</strong><p>Uniquement les besoins où ce partenaire est déjà candidat.</p></section><section><small>Propositions</small><strong>{quotes.length}</strong><p>Devis déjà enregistrés dans la démo.</p></section><section><small>Clients concernés</small><strong>{orgs.length}</strong><p>Entreprises reliées via ces demandes.</p></section><section><small>Agenda</small><strong>{meetings.length}</strong><p>Rendez-vous des entreprises concernées.</p></section></div></>
 if(kind==='demandes') return <><PageHeader eyebrow="Demandes" title="Opportunités qualifiées." description="Le partenaire voit le besoin et le contexte, pas un annuaire générique."/><div className="expert-list">{needs.map(n=><article key={n.id}><small>{n.categoryLabel} · {n.location}</small><h2>{n.title}</h2><p>{n.description}</p><div>{providerReasons(provider,n).map(r=><span key={r}>{r}</span>)}</div></article>)}</div></>
 if(kind==='missions') return <><PageHeader eyebrow="Missions" title="Missions reliées aux clients concernés." description="Une mission n’apparaît que si son entreprise est reliée aux demandes de ce partenaire dans la démo."/><div className="expert-list">{state.missions.filter(m=>orgIds.has(m.orgId)).map(m=><article key={m.id}><small>{m.code} · {m.status}</small><h2>{m.title}</h2><p>{m.owner} · {m.milestones.filter(x=>x.status==='fait').length}/{m.milestones.length} jalons terminés</p></article>)}</div></>
 if(kind==='clients') return <><PageHeader eyebrow="Clients" title="Entreprises reliées." description="La relation client reste liée aux demandes et missions."/><div className="expert-list">{orgs.map(o=><article key={o.id}><small>{o.sector} · {o.city}</small><h2>{o.name}</h2><p>{o.kind} · {o.size}</p></article>)}</div></>
 if(kind==='agenda') return <><PageHeader eyebrow="Agenda" title="Rendez-vous en contexte." description="L’agenda est relié aux entreprises et dossiers concernés."/><div className="expert-list">{meetings.map(m=><article key={m.id}><small>{new Date(m.at).toLocaleString('fr-FR')}</small><h2>{m.title}</h2><p>{m.location} · {m.status}</p></article>)}</div></>
 if(kind==='propositions') return <><PageHeader eyebrow="Propositions" title="Devis et décisions." description="Les propositions existantes restent rattachées à un besoin précis."/><div className="expert-list">{quotes.map(q=>{const n=state.needs.find(x=>x.id===q.needId);return <article key={q.id}><small>{q.status} · {q.delayWeeks} semaine(s)</small><h2>{q.amount.toLocaleString('fr-MA')} €</h2><p>{n?.title} · valable jusqu’au {new Date(q.validUntil).toLocaleDateString('fr-FR')}</p></article>})}</div></>
 if(kind==='documents') return <><PageHeader eyebrow="Documents" title="Documents liés aux dossiers." description="Pas de bibliothèque isolée : chaque pièce reste rattachée à une entreprise concernée."/><div className="expert-list">{docs.map(d=><article key={d.id}><small>{d.kind} · {d.status}</small><h2>{d.name}</h2><p>{d.comment||'Aucun commentaire.'}</p></article>)}</div></>
 if(kind==='performance') return <><PageHeader eyebrow="Performance" title="Preuves issues des données disponibles." description="Aucun score artificiel : volumes et états sont dérivés des données existantes."/><div className="expert-home-grid"><section><small>Demandes</small><strong>{needs.length}</strong></section><section><small>Devis acceptés</small><strong>{quotes.filter(q=>q.status==='accepte').length}</strong></section><section><small>Références</small><strong>{provider.references.length}</strong></section><section><small>Avis enregistrés</small><strong>{provider.reviews}</strong></section></div></>
 return <><PageHeader eyebrow="Profil" title={provider.name} description="La confiance doit être visible proportionnellement au risque de décision."/><div className="expert-profile"><section><small>CATÉGORIE</small><strong>{provider.categoryLabel}</strong></section><section><small>LOCALISATION</small><strong>{provider.city}</strong></section><section><small>VÉRIFICATION</small><strong>{provider.verification}</strong></section><section><small>ASSURANCE</small><strong>{provider.insurance?'Déclarée':'Non renseignée'}</strong></section><section className="wide"><small>RÉFÉRENCES</small><p>{provider.references.join(' · ')||'Aucune référence renseignée.'}</p></section></div></>
}
